export const UsersData = [
  {
    id: 1,
    idNumber: "16j21113",
    firstName: "Malak",
    middleName: "Ibrahim",
    lastName: "al-Jabri",
    age: 21,
    gender: "female",
    email: "Malak@utas.edu.om",
    userType: "student",
    password: "123456",
  },
  {
    id: 2,
    idNumber: "46J211",
    firstName: "Zamzam",
    middleName: "Suhail",
    lastName: "Tabook",
    age: 23,
    gender: "female",
    email: "Zamzam@utas.edu.om",
    userType: "student",
    password: "123456",
  },
  {
    id: 3,
    idNumber: "S1003",
    firstName: "Ahmed",
    middleName: "Ali",
    lastName: "Jaboob",
    age: 44,
    gender: "male",
    email: "ahmed@utas.edu.om",
    userType: "Advisor",
    password: "123456",
  },
];
